/**
 * Module kadre-appkit — backend macOS Desktop via FFM JVM 25 + kextract.
 *
 * Target: jvm only.
 * This module implements the kadre-core interfaces for AppKit (NSWindow,
 * NSApplication, NSView layer-backed) using the Foreign Function &
 * Memory API (JEP 454) generated by kextract.
 *
 * Upstream dependency: kadre-core (jvm sourceSet only, via jvmMain).
 */
plugins {
    id("org.jetbrains.kotlin.multiplatform")
    id("ygdrasil.conventions.kmp-publish")
}

kotlin {
    jvmToolchain(25)

    jvm()

    sourceSets {
        jvmMain {
            dependencies {
                api(project(":kadre-core"))
                api(project(":ffi:objc"))
            }
        }
        jvmTest {
            dependencies {
                implementation(kotlin("test"))
            }
        }
    }
}
