/**
 * ffi:objc — macOS ObjC runtime bindings (libobjc.dylib).
 *
 * Generated by kextract from /usr/include/objc/ and /System/Library/Frameworks/AppKit.framework/Headers/.
 */
plugins {
    id("org.jetbrains.kotlin.multiplatform")
}

kotlin {
    jvmToolchain(25)
    jvm()

    sourceSets {
        jvmMain { dependencies { } }
    }
}
