/**
 * Win32Runtime — FFM runtime stub for the Win32 bindings.
 *
 * This module provides the entry point for FFM calls to the Win32 API.
 * The full implementation will be generated by kextract in Sprint 3 once
 * the Windows SDK is configured in the CI/CD pipeline.
 *
 * Planned architecture (Sprint 3):
 *  - Loading of user32.dll, kernel32.dll, gdi32.dll via FFM SymbolLookup
 *  - Typed wrappers around the FFM MethodHandles for CreateWindowEx,
 *    RegisterClassEx, DefWindowProc, ShowWindow, UpdateWindow, etc.
 *  - Win32 message loop (GetMessage / TranslateMessage / DispatchMessage)
 *    integrated with the kadre-core EventLoop.
 *
 * Reference: https://learn.microsoft.com/en-us/windows/win32/learnwin32/
 *
 * TODO Sprint 3: Replace this stub with Win32_h.kt generated by kextract +
 *   the implementation of [org.graphiks.kadre.core.EventLoop] and
 *   [org.graphiks.kadre.core.Window].
 */
package org.graphiks.kadre.win32.bindings

/**
 * Singleton entry point for the Win32 runtime via FFM.
 *
 * Provides access to the system Win32 libraries (user32, kernel32, gdi32)
 * and to the FFM symbols required to create and manage native windows.
 *
 * Planned usage (Sprint 3):
 * ```kotlin
 * val hwnd = Win32Runtime.createWindow("My Window", 800, 600)
 * Win32Runtime.runMessageLoop()
 * ```
 *
 * Note: This object is a stub — all methods throw [NotImplementedError]
 * until the full implementation in Sprint 3.
 */
object Win32Runtime {

    /**
     * Name of the User32 library (window and message management).
     *
     * Will be used by SymbolLookup.libraryLookup("user32", Arena.global()) in Sprint 3.
     */
    const val USER32_LIB = "user32"

    /**
     * Name of the Kernel32 library (basic system functions).
     *
     * Will be used for GetModuleHandle, ExitProcess, etc.
     */
    const val KERNEL32_LIB = "kernel32"

    /**
     * Name of the GDI32 library (Graphics Device Interface).
     *
     * Will be used for GDI drawing operations if needed.
     */
    const val GDI32_LIB = "gdi32"

    /**
     * Indicates whether the runtime is running on Windows.
     *
     * Allows consuming modules to check the availability of the Win32 backend
     * without triggering a library load.
     */
    val isAvailable: Boolean
        get() = System.getProperty("os.name")?.startsWith("Windows") == true
}
