/**
 * Type aliases for the fundamental Win32 types.
 *
 * These types are Kotlin aliases of the C/Win32 primitive types. They will be used
 * by the FFM bindings generated by kextract in Sprint 3 (requires Windows SDK).
 *
 * Reference: https://learn.microsoft.com/en-us/windows/win32/winprog/windows-data-types
 *
 * Naming convention:
 *  - The names match the official Win32 typedefs (windef.h, minwindef.h).
 *  - Opaque handles (HWND, HINSTANCE, …) are represented as [Long] because
 *    the JVM has no native pointer type; MemorySegment will be used
 *    in the real FFM bindings (kextract Sprint 3).
 *  - BOOL is mapped to [Int] (not [Boolean]) to match exactly
 *    the Win32 semantics (0 = FALSE, non-zero = TRUE).
 *
 * TODO Sprint 3: Replace the Long/Int aliases with the MemorySegments generated
 *   by kextract once the Windows SDK is configured in the CI pipeline.
 */
package org.graphiks.kadre.win32.bindings

// ── Unsigned integers ─────────────────────────────────────────────────────────

/**
 * DWORD — 32-bit unsigned integer (unsigned long in C).
 *
 * Used for window style codes, message identifiers,
 * error return values (GetLastError), etc.
 */
typealias DWORD = Long

/**
 * WORD — 16-bit unsigned integer (unsigned short in C).
 *
 * Used for resource identifiers, virtual key codes, etc.
 */
typealias WORD = Int

/**
 * UINT — 32-bit unsigned integer (unsigned int in C).
 *
 * Used for Windows message identifiers (WM_*, etc.).
 */
typealias UINT = Long

/**
 * ULONG_PTR — pointer-sized unsigned integer (size_t in C).
 *
 * Used for the wParam parameters of Windows messages.
 */
typealias ULONG_PTR = Long

// ── Signed integers ─────────────────────────────────────────────────────────

/**
 * LONG — 32-bit signed integer (long in C, always 32-bit on Windows).
 *
 * Used in the RECT structures (left, top, right, bottom), POINT, etc.
 */
typealias LONG = Int

/**
 * LONG_PTR — pointer-sized signed integer (ptrdiff_t in C).
 *
 * Used for the lParam parameters of Windows messages and extended styles.
 */
typealias LONG_PTR = Long

/**
 * LRESULT — return value of a window procedure (LONG_PTR).
 *
 * Returned by WindowProc and DefWindowProc.
 */
typealias LRESULT = Long

/**
 * WPARAM — "word param" message parameter (UINT_PTR in C).
 *
 * First message parameter (e.g. virtual key for WM_KEYDOWN).
 */
typealias WPARAM = Long

/**
 * LPARAM — "long param" message parameter (LONG_PTR in C).
 *
 * Second message parameter (e.g. coordinates for WM_MOUSEMOVE).
 */
typealias LPARAM = Long

// ── Win32 boolean ─────────────────────────────────────────────────────────────

/**
 * BOOL — 32-bit integer representing a Win32 boolean (int in C).
 *
 * 0 = FALSE, any non-zero value = TRUE.
 * Intentionally [Int] and not [Boolean] to match the exact
 * Win32 semantics (some functions return non-0/1 values).
 */
typealias BOOL = Int

// ── Opaque handles ────────────────────────────────────────────────────────────

/**
 * HWND — handle to a Win32 window.
 *
 * Opaque in C; represented as [Long] (64-bit pointer address).
 * Will be replaced by MemorySegment in the generated FFM bindings (Sprint 3).
 */
typealias HWND = Long

/**
 * HINSTANCE — handle to an application instance (module).
 *
 * Passed to WinMain and used in RegisterClassEx / CreateWindowEx.
 */
typealias HINSTANCE = Long

/**
 * HMODULE — handle to a loaded module (equivalent to HINSTANCE).
 *
 * Returned by GetModuleHandle, LoadLibrary, etc.
 */
typealias HMODULE = Long

/**
 * HICON — handle to a Win32 icon.
 *
 * Used in WNDCLASSEX to specify the window icons.
 */
typealias HICON = Long

/**
 * HCURSOR — handle to a Win32 cursor.
 *
 * Used in WNDCLASSEX (hCursor) and SetCursor.
 */
typealias HCURSOR = Long

/**
 * HBRUSH — handle to a Win32 GDI brush.
 *
 * Used for the background color in WNDCLASSEX (hbrBackground).
 */
typealias HBRUSH = Long

/**
 * HDC — handle to a Device Context (GDI graphics context).
 *
 * Returned by GetDC, BeginPaint, CreateCompatibleDC, etc.
 */
typealias HDC = Long

/**
 * HMENU — handle to a Win32 menu.
 *
 * Passed to CreateWindowEx as the menu parameter.
 */
typealias HMENU = Long

/**
 * ATOM — integer identifier returned by RegisterClassEx.
 *
 * Used to identify a registered window class.
 */
typealias ATOM = Int
