/**
 * ffi:x11 — Linux X11 bindings (libX11.so, libXext.so, libXrandr.so).
 *
 * Generated by kextract from X11/Xlib.h and related headers.
 */
plugins {
    id("org.jetbrains.kotlin.multiplatform")
}

kotlin {
    jvmToolchain(25)
    jvm()

    sourceSets {
        jvmMain { dependencies { } }
    }
}
