package org.graphiks.kadre.appkit

import org.graphiks.kadre.appkit.bindings.NSApplication
import org.graphiks.kadre.appkit.bindings.NSApplicationDelegate
import org.graphiks.kadre.appkit.bindings.NSEvent
import org.graphiks.kadre.appkit.bindings.NSView
import org.graphiks.kadre.appkit.bindings.NSWindow
import org.graphiks.kadre.appkit.bindings.NSWindowDelegate
import org.graphiks.kadre.appkit.bindings.ObjCRuntime
import kotlin.test.Test
import kotlin.test.assertNotNull

/**
 * Smoke test — verifies that the Kotlin/FFM bindings generated by kextract v0.0.0-test6
 * compile correctly and that the AppKit types are accessible.
 *
 * Note: no real Obj-C object instantiation is performed here (that would
 * require a macOS thread with an autorelease pool and the AppKit library
 * loaded). This test only validates the compilation and readability of the
 * generated companions/interfaces.
 */
class SmokeTest {

    @Test
    fun `les classes AppKit generees sont accessibles`() {
        // Verify that the companions exist and are referenceable
        // (no real ObjC call — just checking that the types compile)
        val nsApplicationClass: kotlin.reflect.KClass<NSApplication> = NSApplication::class
        val nsWindowClass: kotlin.reflect.KClass<NSWindow> = NSWindow::class
        val nsViewClass: kotlin.reflect.KClass<NSView> = NSView::class
        val nsEventClass: kotlin.reflect.KClass<NSEvent> = NSEvent::class

        assertNotNull(nsApplicationClass)
        assertNotNull(nsWindowClass)
        assertNotNull(nsViewClass)
        assertNotNull(nsEventClass)
    }

    @Test
    fun `les interfaces delegate AppKit sont importables`() {
        // Verify that the NSApplicationDelegate and NSWindowDelegate protocols
        // are generated as accessible Kotlin interfaces
        val appDelegateClass: kotlin.reflect.KClass<NSApplicationDelegate> = NSApplicationDelegate::class
        val windowDelegateClass: kotlin.reflect.KClass<NSWindowDelegate> = NSWindowDelegate::class

        assertNotNull(appDelegateClass)
        assertNotNull(windowDelegateClass)
    }

    @Test
    fun `ObjCRuntime est accessible`() {
        // Verify that the FFM/ObjC runtime bridge compiles
        val runtime: ObjCRuntime = ObjCRuntime
        assertNotNull(runtime)
    }
}
