/**
 * ffi:wayland — Linux Wayland bindings (libwayland-client.so, protocol extensions).
 *
 * Generated by kextract from wayland-client.h, xdg-shell protocols, etc.
 */
plugins {
    id("org.jetbrains.kotlin.multiplatform")
}

kotlin {
    jvmToolchain(25)
    jvm()

    sourceSets {
        jvmMain { dependencies { } }
    }
}
