/**
 * ffi:win32 — Windows Win32 bindings (user32.dll, kernel32.dll, gdi32.dll).
 *
 * Generated by kextract from the Windows SDK.
 */
plugins {
    id("org.jetbrains.kotlin.multiplatform")
}

tasks.withType<Test>().configureEach {
    jvmArgs("--enable-native-access=ALL-UNNAMED")
}

kotlin {
    jvmToolchain(25)
    jvm()

    sourceSets {
        jvmMain { dependencies { } }
        jvmTest { dependencies { implementation(kotlin("test")) } }
    }
}
