/**
 * Loads the bundled libkadre-xdg.so so the xdg-shell interface symbols
 * (xdg_wm_base_interface, xdg_surface_interface, xdg_toplevel_interface) become resolvable.
 *
 * Those symbols are NOT exported by libwayland-client (xdg-shell is a protocol extension whose
 * tables are generated by wayland-scanner). We ship a small generated shared object that defines
 * them — see docker/wayland-codegen/ — and System.load() it here. Its NEEDED entry pulls in
 * libwayland-client.so.0 transitively. Once loaded, the kextract-generated bindings resolve the
 * symbols via SymbolLookup.loaderLookup().
 *
 * The .so is architecture-specific (linux-<arch>); load fails gracefully on other platforms so
 * the module stays inert on macOS/Windows.
 */
package org.graphiks.kadre.wayland

import java.io.File

internal object WaylandXdgLib {

    /** True once libkadre-xdg.so has been loaded and its interface symbols are resolvable. */
    val loaded: Boolean by lazy { tryLoad() }

    private fun tryLoad(): Boolean = runCatching {
        val arch = when (val a = System.getProperty("os.arch")?.lowercase()) {
            "amd64", "x86_64" -> "x86_64"
            "aarch64", "arm64" -> "aarch64"
            else -> a ?: return@runCatching false
        }
        val resource = "/native/linux-$arch/libkadre-xdg.so"
        val stream = WaylandXdgLib::class.java.getResourceAsStream(resource)
        if (stream == null) {
            System.err.println("[kadre-wayland] libkadre-xdg.so not found on classpath: $resource")
            return@runCatching false
        }

        // Extract to a temp file (System.load needs a real filesystem path).
        val tmp = File.createTempFile("libkadre-xdg", ".so").apply { deleteOnExit() }
        stream.use { input -> tmp.outputStream().use { output -> input.copyTo(output) } }

        System.load(tmp.absolutePath)
        true
    }.getOrElse { e ->
        System.err.println("[kadre-wayland] failed to load libkadre-xdg.so: $e")
        false
    }
}
