package org.graphiks.kadre.x11.binding

import java.lang.foreign.Arena
import java.lang.foreign.FunctionDescriptor
import java.lang.foreign.SymbolLookup
import java.lang.foreign.ValueLayout
import java.lang.invoke.MethodHandle
import java.lang.invoke.MethodHandles

private val generatedLookup = MethodHandles.lookup()
private val generatedClass = Class.forName(
    "org.graphiks.kffi.x11.generated.Xlib_hKt",
    false,
    Thread.currentThread().contextClassLoader,
)
private val constantsClass = Class.forName(
    "org.graphiks.kffi.x11.generated.X11_constants_hKt",
    false,
    Thread.currentThread().contextClassLoader,
)
private val ximConstantsClass = Class.forName(
    "org.graphiks.kffi.x11.generated.X11_xim_constantsKt",
    false,
    Thread.currentThread().contextClassLoader,
)

/**
 * Resolves a function from the generated kffi-x11 facade.
 *
 * kffi-x11 owns the native symbol lookup and ABI descriptors. This small
 * adapter only preserves the nullable MethodHandle API used by Kadre's
 * platform code while the backend is migrated incrementally.
 */
private fun generatedFunction(name: String): MethodHandle? = try {
    val method = generatedClass.methods.single { it.name == name }
    generatedLookup.unreflect(method)
} catch (_: Throwable) {
    null
}

val libX11: SymbolLookup? by lazy {
    try {
        SymbolLookup.libraryLookup("libX11.so.6", Arena.global())
    } catch (_: Throwable) {
        null
    }
}

// Functions generated by kffi-x11.
val xOpenDisplay: MethodHandle? by lazy { generatedFunction("XOpenDisplay") }
val xConnectionNumber: MethodHandle? by lazy { generatedFunction("XConnectionNumber") }
val xCloseDisplay: MethodHandle? by lazy { generatedFunction("XCloseDisplay") }
val xRootWindow: MethodHandle? by lazy { generatedFunction("XRootWindow") }
val xDefaultRootWindow: MethodHandle? by lazy { generatedFunction("XDefaultRootWindow") }
val xCreateSimpleWindow: MethodHandle? by lazy { generatedFunction("XCreateSimpleWindow") }
val xSelectInput: MethodHandle? by lazy { generatedFunction("XSelectInput") }
val xQueryKeymap: MethodHandle? by lazy { generatedFunction("XQueryKeymap") }
val xDestroyWindow: MethodHandle? by lazy { generatedFunction("XDestroyWindow") }
val xFlush: MethodHandle? by lazy { generatedFunction("XFlush") }
val xPending: MethodHandle? by lazy { generatedFunction("XPending") }
val xNextEvent: MethodHandle? by lazy { generatedFunction("XNextEvent") }
val xStoreName: MethodHandle? by lazy { generatedFunction("XStoreName") }
val xInternAtom: MethodHandle? by lazy { generatedFunction("XInternAtom") }
val xSetWMProtocols: MethodHandle? by lazy { generatedFunction("XSetWMProtocols") }
val xMapWindow: MethodHandle? by lazy { generatedFunction("XMapWindow") }
val xRaiseWindow: MethodHandle? by lazy { generatedFunction("XRaiseWindow") }
val xSendEvent: MethodHandle? by lazy { generatedFunction("XSendEvent") }
val xResizeWindow: MethodHandle? by lazy { generatedFunction("XResizeWindow") }
val xMoveWindow: MethodHandle? by lazy { generatedFunction("XMoveWindow") }
val xIconifyWindow: MethodHandle? by lazy { generatedFunction("XIconifyWindow") }
val xChangeProperty: MethodHandle? by lazy { generatedFunction("XChangeProperty") }
val xDeleteProperty: MethodHandle? by lazy { generatedFunction("XDeleteProperty") }
val xGetWindowProperty: MethodHandle? by lazy { generatedFunction("XGetWindowProperty") }
val xFree: MethodHandle? by lazy { generatedFunction("XFree") }
val xGetGeometry: MethodHandle? by lazy { generatedFunction("XGetGeometry") }
val xTranslateCoordinates: MethodHandle? by lazy { generatedFunction("XTranslateCoordinates") }
val xUnmapWindow: MethodHandle? by lazy { generatedFunction("XUnmapWindow") }
val xkbSetDetectableAutoRepeat: MethodHandle? by lazy {
    generatedFunction("XkbSetDetectableAutoRepeat")
}
val xResourceManagerString: MethodHandle? by lazy { generatedFunction("XResourceManagerString") }
val xCreateFontCursor: MethodHandle? by lazy { generatedFunction("XCreateFontCursor") }
val xDefineCursor: MethodHandle? by lazy { generatedFunction("XDefineCursor") }
val xUndefineCursor: MethodHandle? by lazy { generatedFunction("XUndefineCursor") }
val xCreateBitmapFromData: MethodHandle? by lazy { generatedFunction("XCreateBitmapFromData") }
val xCreatePixmapCursor: MethodHandle? by lazy { generatedFunction("XCreatePixmapCursor") }
val xFreePixmap: MethodHandle? by lazy { generatedFunction("XFreePixmap") }
val xFreeCursor: MethodHandle? by lazy { generatedFunction("XFreeCursor") }
val xGrabPointer: MethodHandle? by lazy { generatedFunction("XGrabPointer") }
val xUngrabPointer: MethodHandle? by lazy { generatedFunction("XUngrabPointer") }
val xQueryPointer: MethodHandle? by lazy { generatedFunction("XQueryPointer") }
val xWarpPointer: MethodHandle? by lazy { generatedFunction("XWarpPointer") }
val xGetWMHints: MethodHandle? by lazy { generatedFunction("XGetWMHints") }
val xAllocWMHints: MethodHandle? by lazy { generatedFunction("XAllocWMHints") }
val xSetWMHints: MethodHandle? by lazy { generatedFunction("XSetWMHints") }
val xShapeCombineRectangles: MethodHandle? by lazy {
    generatedFunction("XShapeCombineRectangles")
}
val xChangeWindowAttributes: MethodHandle? by lazy {
    generatedFunction("XChangeWindowAttributes")
}
val xOpenIM: MethodHandle? by lazy { generatedFunction("XOpenIM") }
val xCloseIM: MethodHandle? by lazy { generatedFunction("XCloseIM") }
val xDestroyIC: MethodHandle? by lazy { generatedFunction("XDestroyIC") }
val xConvertSelection: MethodHandle? by lazy { generatedFunction("XConvertSelection") }
val xSetICFocus: MethodHandle? by lazy { generatedFunction("XSetICFocus") }
val xUnsetICFocus: MethodHandle? by lazy { generatedFunction("XUnsetICFocus") }
val xFilterEvent: MethodHandle? by lazy { generatedFunction("XFilterEvent") }
val xShmQueryExtension: MethodHandle? by lazy { generatedFunction("XShmQueryExtension") }
val xShmCreateImage: MethodHandle? by lazy { generatedFunction("XShmCreateImage") }
val xShmAttach: MethodHandle? by lazy { generatedFunction("XShmAttach") }
val xShmDetach: MethodHandle? by lazy { generatedFunction("XShmDetach") }
val xShmGetImage: MethodHandle? by lazy { generatedFunction("XShmGetImage") }
val xGetImage: MethodHandle? by lazy { generatedFunction("XGetImage") }
val xDestroyImage: MethodHandle? by lazy { generatedFunction("XDestroyImage") }
val xDefaultScreen: MethodHandle? by lazy { generatedFunction("XDefaultScreen") }
val xDefaultVisual: MethodHandle? by lazy { generatedFunction("XDefaultVisual") }
val xDefaultDepth: MethodHandle? by lazy { generatedFunction("XDefaultDepth") }
val xQueryTree: MethodHandle? by lazy { generatedFunction("XQueryTree") }
val xGetWindowAttributes: MethodHandle? by lazy { generatedFunction("XGetWindowAttributes") }
val xSync: MethodHandle? by lazy { generatedFunction("XSync") }
val xCompositeNameWindowPixmap: MethodHandle? by lazy {
    generatedFunction("XCompositeNameWindowPixmap")
}
val xLookupString: MethodHandle? by lazy { generatedFunction("XLookupString") }

val xCreateIC: MethodHandle? by lazy { generatedFunction("XCreateIC") }
val xSetICValues: MethodHandle? by lazy { generatedFunction("XSetICValues") }
val xQueryBestCursor: MethodHandle? by lazy { generatedFunction("XQueryBestCursor") }

// Values exposed by Xlib.h and cursorfont.h are read from the generated binding.
private fun generatedConstant(name: String): Any? = try {
    generatedClass.methods.firstOrNull { it.name == name }?.invoke(null)
        ?: constantsClass.methods.first { it.name == name }.invoke(null)
} catch (_: Throwable) {
    null
}

private fun generatedInt(name: String, fallback: Int): Int =
    (generatedConstant(name) as? Int) ?: fallback

private fun generatedLong(name: String, fallback: Long): Long =
    (generatedConstant(name) as? Long) ?: fallback

private fun generatedString(name: String, fallback: String): String = try {
    (ximConstantsClass.getField(name).get(null) as? String) ?: fallback
} catch (_: Throwable) {
    fallback
}

val KeyPress: Int = generatedInt("KeyPress", 2)
val KeyRelease: Int = generatedInt("KeyRelease", 3)
val ButtonPress: Int = generatedInt("ButtonPress", 4)
val ButtonRelease: Int = generatedInt("ButtonRelease", 5)
val MotionNotify: Int = generatedInt("MotionNotify", 6)
val EnterNotify: Int = generatedInt("EnterNotify", 7)
val LeaveNotify: Int = generatedInt("LeaveNotify", 8)
val FocusIn: Int = generatedInt("FocusIn", 9)
val FocusOut: Int = generatedInt("FocusOut", 10)
val Expose: Int = generatedInt("Expose", 12)
val VisibilityNotify: Int = generatedInt("VisibilityNotify", 15)
val SelectionNotify: Int = generatedInt("SelectionNotify", 31)
val DestroyNotify: Int = generatedInt("DestroyNotify", 17)
val ConfigureNotify: Int = generatedInt("ConfigureNotify", 22)
val ClientMessage: Int = generatedInt("ClientMessage", 33)

val KeyPressMask: Long = generatedLong("KeyPressMask", 1L)
val KeyReleaseMask: Long = generatedLong("KeyReleaseMask", 2L)
val ButtonPressMask: Long = generatedLong("ButtonPressMask", 4L)
val ButtonReleaseMask: Long = generatedLong("ButtonReleaseMask", 8L)
val EnterWindowMask: Long = generatedLong("EnterWindowMask", 16L)
val LeaveWindowMask: Long = generatedLong("LeaveWindowMask", 32L)
val PointerMotionMask: Long = generatedLong("PointerMotionMask", 64L)
val ExposureMask: Long = generatedLong("ExposureMask", 32768L)
val VisibilityChangeMask: Long = generatedLong("VisibilityChangeMask", 65536L)
val StructureNotifyMask: Long = generatedLong("StructureNotifyMask", 131072L)
val SubstructureNotifyMask: Long = generatedLong("SubstructureNotifyMask", 524288L)
val SubstructureRedirectMask: Long = generatedLong("SubstructureRedirectMask", 1048576L)
val FocusChangeMask: Long = generatedLong("FocusChangeMask", 2097152L)
val CWOverrideRedirect: Long = generatedLong("CWOverrideRedirect", 1L shl 9)

val XC_left_ptr: Int = generatedInt("XC_left_ptr", 68)
val XC_hand2: Int = generatedInt("XC_hand2", 60)
val XC_xterm: Int = generatedInt("XC_xterm", 152)
val XC_crosshair: Int = generatedInt("XC_crosshair", 34)
val XC_fleur: Int = generatedInt("XC_fleur", 52)
val XC_watch: Int = generatedInt("XC_watch", 150)
val XC_X_cursor: Int = generatedInt("XC_X_cursor", 0)
val XC_hand1: Int = generatedInt("XC_hand1", 58)
val XC_top_side: Int = generatedInt("XC_top_side", 138)
val XC_bottom_side: Int = generatedInt("XC_bottom_side", 16)
val XC_right_side: Int = generatedInt("XC_right_side", 96)
val XC_left_side: Int = generatedInt("XC_left_side", 70)
val XC_top_right_corner: Int = generatedInt("XC_top_right_corner", 136)
val XC_top_left_corner: Int = generatedInt("XC_top_left_corner", 134)
val XC_bottom_right_corner: Int = generatedInt("XC_bottom_right_corner", 14)
val XC_bottom_left_corner: Int = generatedInt("XC_bottom_left_corner", 12)
val XC_question_arrow: Int = generatedInt("XC_question_arrow", 30)
val XC_plus: Int = generatedInt("XC_plus", 58)
val XC_sb_h_double_arrow: Int = generatedInt("XC_sb_h_double_arrow", 108)
val XC_sb_v_double_arrow: Int = generatedInt("XC_sb_v_double_arrow", 116)

val XIMPreeditArea: Long = generatedLong("XIMPreeditArea", 0x0001)
val XIMPreeditCallbacks: Long = generatedLong("XIMPreeditCallbacks", 0x0002)
val XIMPreeditPosition: Long = generatedLong("XIMPreeditPosition", 0x0004)
val XIMPreeditNothing: Long = generatedLong("XIMPreeditNothing", 0x0008)
val XIMStatusNothing: Long = generatedLong("XIMStatusNothing", 0x0400)
val AnyPropertyType: Long = generatedLong("AnyPropertyType", 0L)

val XNInputStyle: String = generatedString("XNInputStyle", "inputStyle")
val XNClientWindow: String = generatedString("XNClientWindow", "clientWindow")
val XNFocusWindow: String = generatedString("XNFocusWindow", "focusWindow")
val XNPreeditAttributes: String = generatedString("XNPreeditAttributes", "preeditAttributes")
val XNArea: String = generatedString("XNArea", "area")
val XNAreaNeeded: String = generatedString("XNAreaNeeded", "areaNeeded")
val XNSpotLocation: String = generatedString("XNSpotLocation", "spotLocation")
val XNPreeditStartCallback: String = generatedString("XNPreeditStartCallback", "preeditStartCallback")
val XNPreeditDrawCallback: String = generatedString("XNPreeditDrawCallback", "preeditDrawCallback")
val XNPreeditDoneCallback: String = generatedString("XNPreeditDoneCallback", "preeditDoneCallback")
val XNCommitStringCallback: String = generatedString("XNCommitStringCallback", "commitStringCallback")

val XIM_PROC_DESCRIPTOR: FunctionDescriptor = FunctionDescriptor.ofVoid(
    ValueLayout.ADDRESS,
    ValueLayout.ADDRESS,
    ValueLayout.ADDRESS,
)

val XSHM_ZPIXMAP: Int = generatedInt("XSHM_ZPIXMAP", 2)
val IsViewable: Int = generatedInt("IsViewable", 2)
val Xlib_ZPixmap: Int = generatedInt("ZPixmap", 2)
val Xlib_AllPlanes: Long = generatedLong("AllPlanes", -1L)
