package org.graphiks.kadre.x11.binding

import java.lang.foreign.Arena
import java.lang.foreign.FunctionDescriptor
import java.lang.foreign.Linker
import java.lang.foreign.MemoryLayout.PathElement.groupElement
import java.lang.foreign.MemorySegment
import java.lang.foreign.SymbolLookup
import java.lang.foreign.ValueLayout
import java.lang.invoke.MethodHandle
import java.lang.invoke.MethodHandles
import org.graphiks.kadre.ffi.posix.PosixSymbols

private val generatedLookup = MethodHandles.lookup()
private val generatedClass = Class.forName(
    "org.graphiks.kffi.x11.generated.Xlib_hKt",
    false,
    Thread.currentThread().contextClassLoader,
)
private val constantsClass = Class.forName(
    "org.graphiks.kffi.x11.generated.X11_constants_hKt",
    false,
    Thread.currentThread().contextClassLoader,
)

/**
 * Resolves a function from the generated kffi-x11 facade.
 *
 * kffi-x11 owns the native symbol lookup and ABI descriptors. This small
 * adapter only preserves the nullable MethodHandle API used by Kadre's
 * platform code while the backend is migrated incrementally.
 */
private fun generatedFunction(name: String): MethodHandle? = try {
    val method = generatedClass.methods.single { it.name == name }
    generatedLookup.unreflect(method)
} catch (_: Throwable) {
    null
}

val libX11: SymbolLookup? by lazy {
    try {
        SymbolLookup.libraryLookup("libX11.so.6", Arena.global())
    } catch (_: Throwable) {
        null
    }
}

private val linker: Linker = Linker.nativeLinker()

private fun SymbolLookup?.downcall(name: String, descriptor: FunctionDescriptor): MethodHandle? {
    this ?: return null
    return find(name).map { linker.downcallHandle(it, descriptor) }.orElse(null)
}

private fun SymbolLookup?.downcallVariadic(
    name: String,
    descriptor: FunctionDescriptor,
): MethodHandle? {
    this ?: return null
    return find(name).map {
        linker.downcallHandle(it, descriptor, Linker.Option.firstVariadicArg(1))
    }.orElse(null)
}

// Functions generated by kffi-x11.
val xOpenDisplay: MethodHandle? by lazy { generatedFunction("XOpenDisplay") }
val xConnectionNumber: MethodHandle? by lazy { generatedFunction("XConnectionNumber") }
val xCloseDisplay: MethodHandle? by lazy { generatedFunction("XCloseDisplay") }
val xRootWindow: MethodHandle? by lazy { generatedFunction("XRootWindow") }
val xDefaultRootWindow: MethodHandle? by lazy { generatedFunction("XDefaultRootWindow") }
val xCreateSimpleWindow: MethodHandle? by lazy { generatedFunction("XCreateSimpleWindow") }
val xSelectInput: MethodHandle? by lazy { generatedFunction("XSelectInput") }
val xQueryKeymap: MethodHandle? by lazy { generatedFunction("XQueryKeymap") }
val xDestroyWindow: MethodHandle? by lazy { generatedFunction("XDestroyWindow") }
val xFlush: MethodHandle? by lazy { generatedFunction("XFlush") }
val xPending: MethodHandle? by lazy { generatedFunction("XPending") }
val xNextEvent: MethodHandle? by lazy { generatedFunction("XNextEvent") }
val xStoreName: MethodHandle? by lazy { generatedFunction("XStoreName") }
val xInternAtom: MethodHandle? by lazy { generatedFunction("XInternAtom") }
val xSetWMProtocols: MethodHandle? by lazy { generatedFunction("XSetWMProtocols") }
val xMapWindow: MethodHandle? by lazy { generatedFunction("XMapWindow") }
val xRaiseWindow: MethodHandle? by lazy { generatedFunction("XRaiseWindow") }
val xSendEvent: MethodHandle? by lazy { generatedFunction("XSendEvent") }
val xResizeWindow: MethodHandle? by lazy { generatedFunction("XResizeWindow") }
val xMoveWindow: MethodHandle? by lazy { generatedFunction("XMoveWindow") }
val xIconifyWindow: MethodHandle? by lazy { generatedFunction("XIconifyWindow") }
val xChangeProperty: MethodHandle? by lazy { generatedFunction("XChangeProperty") }
val xDeleteProperty: MethodHandle? by lazy { generatedFunction("XDeleteProperty") }
val xGetWindowProperty: MethodHandle? by lazy { generatedFunction("XGetWindowProperty") }
val xFree: MethodHandle? by lazy { generatedFunction("XFree") }
val xGetGeometry: MethodHandle? by lazy { generatedFunction("XGetGeometry") }
val xTranslateCoordinates: MethodHandle? by lazy { generatedFunction("XTranslateCoordinates") }
val xUnmapWindow: MethodHandle? by lazy { generatedFunction("XUnmapWindow") }
val xkbSetDetectableAutoRepeat: MethodHandle? by lazy {
    generatedFunction("XkbSetDetectableAutoRepeat")
}
val xResourceManagerString: MethodHandle? by lazy { generatedFunction("XResourceManagerString") }
val xCreateFontCursor: MethodHandle? by lazy { generatedFunction("XCreateFontCursor") }
val xDefineCursor: MethodHandle? by lazy { generatedFunction("XDefineCursor") }
val xUndefineCursor: MethodHandle? by lazy { generatedFunction("XUndefineCursor") }
val xCreateBitmapFromData: MethodHandle? by lazy { generatedFunction("XCreateBitmapFromData") }
val xCreatePixmapCursor: MethodHandle? by lazy { generatedFunction("XCreatePixmapCursor") }
val xFreePixmap: MethodHandle? by lazy { generatedFunction("XFreePixmap") }
val xFreeCursor: MethodHandle? by lazy { generatedFunction("XFreeCursor") }
val xGrabPointer: MethodHandle? by lazy { generatedFunction("XGrabPointer") }
val xUngrabPointer: MethodHandle? by lazy { generatedFunction("XUngrabPointer") }
val xQueryPointer: MethodHandle? by lazy { generatedFunction("XQueryPointer") }
val xWarpPointer: MethodHandle? by lazy { generatedFunction("XWarpPointer") }
val xGetWMHints: MethodHandle? by lazy { generatedFunction("XGetWMHints") }
val xAllocWMHints: MethodHandle? by lazy { generatedFunction("XAllocWMHints") }
val xSetWMHints: MethodHandle? by lazy { generatedFunction("XSetWMHints") }
val xShapeCombineRectangles: MethodHandle? by lazy {
    generatedFunction("XShapeCombineRectangles")
}
val xChangeWindowAttributes: MethodHandle? by lazy {
    generatedFunction("XChangeWindowAttributes")
}
val xOpenIM: MethodHandle? by lazy { generatedFunction("XOpenIM") }
val xCloseIM: MethodHandle? by lazy { generatedFunction("XCloseIM") }
val xDestroyIC: MethodHandle? by lazy { generatedFunction("XDestroyIC") }
val xConvertSelection: MethodHandle? by lazy { generatedFunction("XConvertSelection") }
val xSetICFocus: MethodHandle? by lazy { generatedFunction("XSetICFocus") }
val xUnsetICFocus: MethodHandle? by lazy { generatedFunction("XUnsetICFocus") }
val xFilterEvent: MethodHandle? by lazy { generatedFunction("XFilterEvent") }

// XCreateIC and XSetICValues are variadic and remain Kadre-specific calls.
val xCreateIC: MethodHandle? by lazy {
    libX11.downcallVariadic(
        "XCreateIC",
        FunctionDescriptor.of(
            ValueLayout.ADDRESS,
            ValueLayout.ADDRESS,
            ValueLayout.ADDRESS, ValueLayout.ADDRESS,
            ValueLayout.ADDRESS, ValueLayout.ADDRESS,
            ValueLayout.ADDRESS, ValueLayout.ADDRESS,
            ValueLayout.ADDRESS, ValueLayout.ADDRESS,
            ValueLayout.ADDRESS, ValueLayout.ADDRESS,
            ValueLayout.ADDRESS, ValueLayout.ADDRESS,
            ValueLayout.ADDRESS, ValueLayout.ADDRESS,
            ValueLayout.ADDRESS,
        ),
    )?.asType(
        java.lang.invoke.MethodType.methodType(
            MemorySegment::class.java,
            MemorySegment::class.java,
            MemorySegment::class.java, MemorySegment::class.java,
            MemorySegment::class.java, MemorySegment::class.java,
            MemorySegment::class.java, MemorySegment::class.java,
            MemorySegment::class.java, MemorySegment::class.java,
            MemorySegment::class.java, MemorySegment::class.java,
            MemorySegment::class.java, MemorySegment::class.java,
            MemorySegment::class.java, MemorySegment::class.java,
            MemorySegment::class.java,
        ),
    )
}

val xSetICValues: MethodHandle? by lazy {
    libX11.downcallVariadic(
        "XSetICValues",
        FunctionDescriptor.of(
            ValueLayout.ADDRESS,
            ValueLayout.ADDRESS,
            ValueLayout.ADDRESS, ValueLayout.ADDRESS,
            ValueLayout.ADDRESS, ValueLayout.ADDRESS,
            ValueLayout.ADDRESS,
        ),
    )
}

// XQueryBestCursor is not present in the current generated snapshot.
val xQueryBestCursor: MethodHandle? by lazy {
    libX11.downcall(
        "XQueryBestCursor",
        FunctionDescriptor.of(
            ValueLayout.JAVA_INT,
            ValueLayout.ADDRESS,
            ValueLayout.JAVA_LONG,
            ValueLayout.JAVA_INT,
            ValueLayout.JAVA_INT,
            ValueLayout.ADDRESS,
            ValueLayout.ADDRESS,
        ),
    )
}

// POSIX poll remains a Kadre helper because it belongs to ffi:posix, not X11.
private val pollCaptureErrno = Linker.Option.captureCallState("errno")
private val pollCaptureLayout = Linker.Option.captureStateLayout()
private val pollErrnoOffset = pollCaptureLayout.byteOffset(groupElement("errno"))
private val nativePoll: MethodHandle? by lazy {
    PosixSymbols.find("poll")?.let { symbol ->
        linker.downcallHandle(
            symbol,
            FunctionDescriptor.of(
                ValueLayout.JAVA_INT,
                ValueLayout.ADDRESS,
                ValueLayout.JAVA_LONG,
                ValueLayout.JAVA_INT,
            ),
            pollCaptureErrno,
        )
    }
}

data class X11NativePollResult(val value: Int, val errno: Int?)

fun invokeX11NativePoll(
    pollFds: MemorySegment,
    count: Long,
    timeoutMillis: Int,
): X11NativePollResult = Arena.ofConfined().use { arena ->
    val poll = nativePoll ?: error("required POSIX symbol 'poll' is unavailable")
    val callState = arena.allocate(pollCaptureLayout)
    val result = poll.invokeExact(callState, pollFds, count, timeoutMillis) as Int
    X11NativePollResult(
        value = result,
        errno = if (result < 0) callState.get(ValueLayout.JAVA_INT, pollErrnoOffset) else null,
    )
}

// Values exposed by Xlib.h and cursorfont.h are read from the generated binding.
private fun generatedConstant(name: String): Any? = try {
    generatedClass.methods.firstOrNull { it.name == name }?.invoke(null)
        ?: constantsClass.methods.first { it.name == name }.invoke(null)
} catch (_: Throwable) {
    null
}

private fun generatedInt(name: String, fallback: Int): Int =
    (generatedConstant(name) as? Int) ?: fallback

private fun generatedLong(name: String, fallback: Long): Long =
    (generatedConstant(name) as? Long) ?: fallback

val KeyPress: Int = generatedInt("KeyPress", 2)
val KeyRelease: Int = generatedInt("KeyRelease", 3)
val ButtonPress: Int = generatedInt("ButtonPress", 4)
val ButtonRelease: Int = generatedInt("ButtonRelease", 5)
val MotionNotify: Int = generatedInt("MotionNotify", 6)
val EnterNotify: Int = generatedInt("EnterNotify", 7)
val LeaveNotify: Int = generatedInt("LeaveNotify", 8)
val FocusIn: Int = generatedInt("FocusIn", 9)
val FocusOut: Int = generatedInt("FocusOut", 10)
val Expose: Int = generatedInt("Expose", 12)
val VisibilityNotify: Int = generatedInt("VisibilityNotify", 15)
val SelectionNotify: Int = generatedInt("SelectionNotify", 31)
val DestroyNotify: Int = generatedInt("DestroyNotify", 17)
val ConfigureNotify: Int = generatedInt("ConfigureNotify", 22)
val ClientMessage: Int = generatedInt("ClientMessage", 33)

val KeyPressMask: Long = generatedLong("KeyPressMask", 1L)
val KeyReleaseMask: Long = generatedLong("KeyReleaseMask", 2L)
val ButtonPressMask: Long = generatedLong("ButtonPressMask", 4L)
val ButtonReleaseMask: Long = generatedLong("ButtonReleaseMask", 8L)
val EnterWindowMask: Long = generatedLong("EnterWindowMask", 16L)
val LeaveWindowMask: Long = generatedLong("LeaveWindowMask", 32L)
val PointerMotionMask: Long = generatedLong("PointerMotionMask", 64L)
val ExposureMask: Long = generatedLong("ExposureMask", 32768L)
val VisibilityChangeMask: Long = generatedLong("VisibilityChangeMask", 65536L)
val StructureNotifyMask: Long = generatedLong("StructureNotifyMask", 131072L)
val SubstructureNotifyMask: Long = generatedLong("SubstructureNotifyMask", 524288L)
val SubstructureRedirectMask: Long = generatedLong("SubstructureRedirectMask", 1048576L)
val FocusChangeMask: Long = generatedLong("FocusChangeMask", 2097152L)
val CWOverrideRedirect: Long = generatedLong("CWOverrideRedirect", 1L shl 9)

val XC_left_ptr: Int = generatedInt("XC_left_ptr", 68)
val XC_hand2: Int = generatedInt("XC_hand2", 60)
val XC_xterm: Int = generatedInt("XC_xterm", 152)
val XC_crosshair: Int = generatedInt("XC_crosshair", 34)
val XC_fleur: Int = generatedInt("XC_fleur", 52)
val XC_watch: Int = generatedInt("XC_watch", 150)
val XC_X_cursor: Int = generatedInt("XC_X_cursor", 0)
val XC_hand1: Int = generatedInt("XC_hand1", 58)
val XC_top_side: Int = generatedInt("XC_top_side", 138)
val XC_bottom_side: Int = generatedInt("XC_bottom_side", 16)
val XC_right_side: Int = generatedInt("XC_right_side", 96)
val XC_left_side: Int = generatedInt("XC_left_side", 70)
val XC_top_right_corner: Int = generatedInt("XC_top_right_corner", 136)
val XC_top_left_corner: Int = generatedInt("XC_top_left_corner", 134)
val XC_bottom_right_corner: Int = generatedInt("XC_bottom_right_corner", 14)
val XC_bottom_left_corner: Int = generatedInt("XC_bottom_left_corner", 12)
val XC_question_arrow: Int = generatedInt("XC_question_arrow", 30)
val XC_plus: Int = generatedInt("XC_plus", 58)
val XC_sb_h_double_arrow: Int = generatedInt("XC_sb_h_double_arrow", 108)
val XC_sb_v_double_arrow: Int = generatedInt("XC_sb_v_double_arrow", 116)

val XIMPreeditArea: Long = generatedLong("XIMPreeditArea", 0x0001)
val XIMPreeditCallbacks: Long = generatedLong("XIMPreeditCallbacks", 0x0004)
val XIMPreeditPosition: Long = generatedLong("XIMPreeditPosition", 0x0008)
val XIMPreeditNothing: Long = generatedLong("XIMPreeditNothing", 0x0010)
val XIMStatusNothing: Long = generatedLong("XIMStatusNothing", 0x0100)

val XNInputStyle = "inputStyle"
val XNClientWindow = "clientWindow"
val XNFocusWindow = "focusWindow"
val XNPreeditAttributes = "preeditAttributes"
val XNArea = "area"
val XNAreaNeeded = "areaNeeded"
val XNSpotLocation = "spotLocation"
val XNPreeditStartCallback = "preeditStartCallback"
val XNPreeditDrawCallback = "preeditDrawCallback"
val XNPreeditDoneCallback = "preeditDoneCallback"
val XNCommitStringCallback = "commitStringCallback"

const val XRECTANGLE_SIZE: Long = 8L
const val XRECTANGLE_ALIGN: Long = 2L
const val XPOINT_SIZE: Long = 4L
const val XPOINT_ALIGN: Long = 2L
const val XIM_CALLBACK_CLIENT_DATA_OFFSET: Long = 0L
const val XIM_CALLBACK_PROC_OFFSET: Long = 8L
const val XIM_CALLBACK_SIZE: Long = 16L
const val PREDRAW_CARET_OFFSET: Long = 0L
const val PREDRAW_CHG_FIRST_OFFSET: Long = 4L
const val PREDRAW_CHG_LENGTH_OFFSET: Long = 8L
const val PREDRAW_TEXT_PTR_OFFSET: Long = 16L
const val XIMTEXT_LENGTH_OFFSET: Long = 0L
const val XIMTEXT_FEEDBACK_OFFSET: Long = 8L
const val XIMTEXT_ENCODING_IS_WCHAR_OFFSET: Long = 16L
const val XIMTEXT_STRING_PTR_OFFSET: Long = 24L
const val PRESTATE_COUNT_OFFSET: Long = 0L

val XIM_PROC_DESCRIPTOR: FunctionDescriptor = FunctionDescriptor.ofVoid(
    ValueLayout.ADDRESS,
    ValueLayout.ADDRESS,
    ValueLayout.ADDRESS,
)

// Layout values not represented by the generated snapshot.
const val XCLIENT_SEND_EVENT_OFFSET: Long = 16L
const val XCLIENT_DISPLAY_OFFSET: Long = 24L
const val XCLIENT_WINDOW_OFFSET: Long = 32L
const val XCLIENT_MESSAGE_TYPE_OFFSET: Long = 40L
const val XCLIENT_FORMAT_OFFSET: Long = 48L
const val XCLIENT_DATA_L0_OFFSET: Long = 56L
const val XCLIENT_DATA_L1_OFFSET: Long = 64L
const val XCLIENT_DATA_L2_OFFSET: Long = 72L
const val XCLIENT_DATA_L3_OFFSET: Long = 80L
const val XCLIENT_DATA_L4_OFFSET: Long = 88L
const val XSELECTION_REQUESTOR_OFFSET: Long = 32L
const val XSELECTION_SELECTION_OFFSET: Long = 40L
const val XSELECTION_TARGET_OFFSET: Long = 48L
const val XSELECTION_PROPERTY_OFFSET: Long = 56L
const val XSETWINDOWATTRIBUTES_SIZE: Long = 112L
const val XSETWINDOWATTRIBUTES_ALIGN: Long = 8L
const val XSETWINDOWATTR_OVERRIDE_REDIRECT_OFFSET: Long = 88L

const val Xlib_ZPixmap: Int = 2
const val Xlib_AllPlanes: Long = -1L
